### ISSUE TITLE
ts-language automatic channel translation not working

### ISSUE THREAD

**Issue by luiizfenix** [TannerReynolds/Translation-Bot#22]
Hi previously i was using the bot perfectly with 3 channels automatically translated by your hosted bot. 

I recently self hosted the bot and invited it to my server but channels aren't translating anymore. 

Do i need any other configuration? 

i have enabled   "tsChannelsEnabled":  true

**Comment by TannerReynolds** [comment]
You now type `ts-[LANGUAGE]` inside the channel topic, rather than the channel name

**Comment by luiizfenix** [comment]
oh okj didnt noticed that, now its working thanks
