### ISSUE TITLE
Auto channel translation reposts emotes

### ISSUE THREAD

**Issue by Afootpluto** [TannerReynolds/Translation-Bot#3]
Any time someone uses only emote(s), the bot posts the emotes again.

**Comment by TannerReynolds** [comment]
What language did you use?

**Comment by Afootpluto** [comment]
Spanish to English

**Comment by TannerReynolds** [comment]
I'm not really seeing the issue here

![translation](http://kpop4.us/z01wbp)

**Comment by Afootpluto** [comment]
I was hoping you can make it were it doesnt repost the emote(s) if it is the only thing in the message. It can easily fill up the chat.

**Comment by TannerReynolds** [comment]
Fixed with 5d5ca2797ae1c9dd0a798d8f665f21b7d7d8e2f7
enclose messages with "<>" to make the bot ignore them.
![fixed](http://kpop4.us/gm0k0s)

**Comment by Afootpluto** [comment]
Thanks
