### ISSUE TITLE
:t Channel Multi language automatic translate

### ISSUE THREAD

**Issue by Rnishanth** [TannerReynolds/Translation-Bot#5]
Hello,

I want to enable automatic translate of few languages like french, german to English. But i do not want to translate English text to be translated to german or french. 

I tired the following -

:t channel fr en
:t channel de en

After these, the french text is still not translated. But German gets translated.  All English is translated to german.
How can i enable multi language to be translated to english but prevent english from being translated.

**Comment by TannerReynolds** [comment]
Multi language support will not happen due to Discord's API ratelimits. 

The reason why doing multiple `:t channel` commands wont work is because each time you run it, is because each time you run it, you're overriding the last entry.
